No disk space h5
VorTECHsa/dynamicio pull request #37
Opened 2022-12-06 16:44 UTC by VRGhost

## Overview

Brief description of the work and why it's relevant

## Key Changes

* Added abc to `foo.py`
* Fixed bug in `buggy_function` in `bar.py`

## Impact

* `Removing support for X I/O --> breaking change!`

## Checklist

The following won't apply in all cases - mark `N/A` next to point if not needed.

- [ ] Appropriate unit tests added/updated
- [ ] Module, function, class docstrings updated
- [ ] Comments added to PR where necessary
- [ ] Interface documentation updated
- [ ] Semantic commits used for this PR, so that a CHANGELOG can be generated from them (don't delete your local branch! when tagging a new release from master)

## Optional Below:

- [ ] Screenshots of actual interactions with live resources. 
- [ ] Performance stats/graphs.

## Release-Steps

- [ ] Merge PR
- [ ] Release new tag

2022-12-15 18:30 UTC, Christos-Hadjinikolis commented on tests/conftest.py
> +            ],
Please oh please dont reformat these!!!

2022-12-16 10:51 UTC, VRGhost commented on tests/conftest.py
> +            ],
Sorry, this was an accident.

2023-01-09 16:16 UTC, Christos-Hadjinikolis commented on dynamicio/mixins/with_s3.py
> +class HDFIo:
Change name please :P

2023-01-09 16:37 UTC, Christos-Hadjinikolis requested changes
LGTM me overall, just minor changes, please see my notes.

2023-01-09 16:37 UTC, Christos-Hadjinikolis commented on dynamicio/mixins/with_s3.py
> +                return no_disk_space_rv
Why not rewrite as: 
```python
        if self.options.pop("no_disk_space", False):
            if file_type == "parquet":
                return self._read_parquet_file(full_path_prefix, self.schema, **self.options)
            elif file_type == "hdf":
                dfs = []
                for fobj in self._iter_s3_files(full_path_prefix, file_ext=".h5", max_memory_use=1024**3):
                    dfs.append(HDFIo().load(fobj))
                df = pd.concat(dfs, ignore_index=True)
                columns = [column for column in df.columns.to_list() if column in self.schema.keys()]
                return df[columns]
            
```

2023-01-09 16:37 UTC, Christos-Hadjinikolis commented on dynamicio/mixins/with_s3.py
> +                return no_disk_space_rv
I would also urge you to encapsulate this: 
```python
                dfs = []
                for fobj in self._iter_s3_files(full_path_prefix, file_ext=".h5", max_memory_use=1024**3):
                    dfs.append(HDFIo().load(fobj))
                df = pd.concat(dfs, ignore_index=True)
                columns = [column for column in df.columns.to_list() if column in self.schema.keys()]
                return df[columns]
``` 
into a dedicated method. But I see your point on doing this later for csv and json files too!

2023-01-09 16:47 UTC, Christos-Hadjinikolis approved these changes

2023-01-09 16:59 UTC, Christos-Hadjinikolis approved these changes

2023-01-09 17:07 UTC, merged