feat: support specifying a subset of fields to read
VorTECHsa/dynamicio pull request #53
Opened 2023-06-12 16:46 UTC by matteo-pallini

Being able to specify a subset of fields to read and only read these is a particularly useful feature. In particular when reading data stored in parquet files, where it is possible to read only the data needed, rather than all of all the time and then remove the one not needed.

## Key Changes

If a subset of fields is specified whenever the IO resources is initialised schema validation is going to be performed only on these fields

## Impact

* introduce a backward compatible feature

## Checklist

The following won't apply in all cases - mark `N/A` next to point if not needed.

- [ ] Module, function, class docstrings updated
- [ ] Interface documentation updated
- [ ] Semantic commits used for this PR, so that a CHANGELOG can be generated from them (don't delete your local branch! when tagging a new release from master)

## Release-Steps

- [ ] Merge PR
- [ ] Release new tag

2023-06-19 15:11 UTC, Christos-Hadjinikolis requested changes

2023-06-19 15:11 UTC, Christos-Hadjinikolis commented on dynamicio/core.py
> +        for col_info in cols_to_validate:
For me, it was a bit hard to parse this. I would rewrite as follows: 

```python
# Get the columns to validate. If no `"columns"` are specified in `self.options`, then default to the schema columns.
requested_columns = self.options.get("columns", self.schema.column_names)

cols_to_validate = []
missing_columns = False

# Iterate over the requested columns
for column in requested_columns:
    # If a requested column is in the schema, add it to the cols_to_validate list
    if column in self.schema.column_names:
        cols_to_validate.append(self.schema.columns[column])
    # If a requested column is not in the schema, log an exception and set missing_columns to True
    else:
        logger.exception(f"The column '{column}' does not belong to the schema")
        missing_columns = True

# If any columns were missing, return False
if missing_columns:
    return False
```
Thoughts?

2023-06-19 15:13 UTC, Christos-Hadjinikolis commented
More importantly, have you tested this version of `dynamicio` with any repo that uses it?

2023-06-19 15:28 UTC, Christos-Hadjinikolis commented on dynamicio/core.py
> +        for col_info in cols_to_validate:
If am not going too far with this, I would dare say you can even extract this logic into a: 

```python 
def __get_columns_to_validate(filtered_columns: List[str, ], default_columns=List[str]): 
   ...
```
method, for readability's sake.

2023-06-20 07:46 UTC, matteo-pallini commented on tests/test_core.py
> +
I am not a big fan of this.... but addressed as requested

2023-06-21 09:10 UTC, Christos-Hadjinikolis approved these changes

2023-06-21 09:33 UTC, merged